const { HTTP_CODES, HTTP_MESSAGES } = require("../helpers/constants");

const { OK, NOT_FOUND, CREATED } = HTTP_CODES;
const { NOT_FOUND_MSG, SUCCESS, DELETED, MISSING_FIELDS, ERROR } = HTTP_MESSAGES;
